"use client";

import {
  Home, Trophy, Award, User, BookOpen, GraduationCap,
  BarChart3, Search, ChevronRight, Bookmark, CheckCircle2,
  Star, Flame, Zap, Target, Brain, Medal, Crown, Sparkles,
  TrendingUp, Clock, ArrowRight, X, ChevronDown, ChevronLeft,
  Menu, Settings, LogOut, Moon, Sun, Calculator, Pi,
  Triangle, Circle, Square, Hexagon, Pentagon,
  Hash, AtSign, Percent, DollarSign, Minus, Plus,
  Divide, Equal, MoreHorizontal, ExternalLink, Copy,
  Share2, Download, Upload, RefreshCw, RotateCcw,
  Eye, EyeOff, Lock, Unlock, Shield, Key,
  Mail, Phone, MapPin, Globe, Link, Image,
  FileText, Folder, FolderOpen, Archive, Tag,
  Layers, LayoutGrid, List, Grid, AlignLeft,
  AlignCenter, AlignRight, Bold, Italic, Underline,
  Code, Terminal, Database, Server, Cloud,
  Wifi, Bluetooth, Battery, Signal, Power,
  Volume2, VolumeX, Mic, MicOff, Camera,
  Video, Film, Music, Headphones, Speaker,
  Printer, Monitor, Smartphone, Tablet, Watch,
} from "lucide-react";

export {
  Home, Trophy, Award, User, BookOpen, GraduationCap,
  BarChart3, Search, ChevronRight, Bookmark, CheckCircle2,
  Star, Flame, Zap, Target, Brain, Medal, Crown, Sparkles,
  TrendingUp, Clock, ArrowRight, X, ChevronDown, ChevronLeft,
  Menu, Settings, LogOut, Moon, Sun, Calculator, Pi,
  Triangle, Circle, Square, Hexagon, Pentagon,
  Hash, AtSign, Percent, DollarSign, Minus, Plus,
  Divide, Equal, MoreHorizontal, ExternalLink, Copy,
  Share2, Download, Upload, RefreshCw, RotateCcw,
  Eye, EyeOff, Lock, Unlock, Shield, Key,
  Mail, Phone, MapPin, Globe, Link, Image,
  FileText, Folder, FolderOpen, Archive, Tag,
  Layers, LayoutGrid, List, Grid, AlignLeft,
  AlignCenter, AlignRight, Bold, Italic, Underline,
  Code, Terminal, Database, Server, Cloud,
  Wifi, Bluetooth, Battery, Signal, Power,
  Volume2, VolumeX, Mic, MicOff, Camera,
  Video, Film, Music, Headphones, Speaker,
  Printer, Monitor, Smartphone, Tablet, Watch,
};
